# Love 3Blue1Brown Animations? Learn How to Create One in Python Using Manim
## TODO
![](images/opening.png)
<figcaption style="text-align: center;">
    <strong>
        All images are by the author unless specified otherwise.
    </strong>
</figcaption>

Do you know how many lines of code went into creating the Essence of Linear Algebra series of 3Blue1Brown?

> 22,466!

With 16 videos in the series and a total of +100 on the channel, these numbers speak volumes of how much the math world is indebted to Grant Sanderson. 



# What is Manim?

Manim stands for *mathematical animation* engine and was created by Grant Sanderson to produce high-precision math animation videos. The main objective of the 3B1B channel and this Python library is to compliment traditional textbook-based math learning with visual intuition.

https://www.youtube.com/watch?v=v0YEaeIClKY

Currently, there are two versions of Manim: [the original library](https://github.com/3b1b/manim) created by Grant and [the forked version](https://github.com/ManimCommunity/manim) maintained by the Manim community. In this post, we will be using the community version since it is better maintained, tested and most importantly, properly documented.

There are many installation options and I think, using the Docker image is the most hassle-free way to interact with the library. Kindly refer to [this page](https://hub.docker.com/r/manimcommunity/manim) for Dockerized installation instructions or [this page](https://docs.manim.community/en/stable/installation.html) for other options so that you can follow along. 

Or, you can just stay and enjoy the content, because there will be some awesome animations!

> Note that the post contains several animations as GIFs and videos, which might slow down their display. You can download the source code of the article from [my GitHub repo](https://github.com/BexTuychiev/medium_stories/tree/master/2021/august/4_manim_basics). The post also refers to several Python OOP concepts that might confuse beginners. If at any point you find yourself struggling, check out [my OOP series](https://ibexorigin.medium.com/list/objectoriented-programming-essentials-for-data-scientists-cf2ff3dc9fc9).

# Higher-level overview of how Manim works

Manim was created as a bridge between [FFmpeg video encoding engine](https://en.wikipedia.org/wiki/FFmpeg) and Python. Since you can't communicate built-in Python data structures to FFmpeg, Manim implements several classes focused on mathematical object representation and animation.

These classes are generally divided into 3 categories: `Scene`, `Mobject` and `Animation`. To explain these concepts more clearly, let's create our very first animation:

```python
from manim import *


class MyFirstAnimation(Scene):
    def construct(self):
        # Create basic mobjects
        star = Star(n=5, fill_color=RED, stroke_color=BLUE)
        circle = Circle(fill_color=DARK_BLUE, fill_opacity=0.8, stroke_color=BLUE)

        # Animate Fade in of the star that takes 2 seconds
        self.play(FadeIn(star, run_time=2))
        # Wait for a second
        self.wait()
        # Transform star into a circle
        self.play(Transform(star, circle))
        self.wait(0.5)
        # Remove the circle by fading it out
        self.play(FadeOut(circle))
```

After you have installed Manim and saved the above code in a script like `scenes.py`, run the following command:

```
manim -pqh scenes.py MyFirstAnimation
```
and you should get this output:

Congratulations! You just made your very first animation! 

Here is the breakdown of this CLI command - adding `-p` to `manim` will enable you to play the video as soon as it is compiled. Combining it with `qh` means render it in high quality. There are 4 quality levels - low (`l`), medium (`m`), high (`h`) and 4k (`k`) with increasing render time. 

If you want a GIF version of the animation, just add `-i` after `-pqh`. Here is a [full list](https://docs.manim.community/en/stable/tutorials/configuration.html) of manim CLI commands.

# Breaking down the basic Manim API

Let's understand the above animation by analyzing the code line by line. 

After importing all manim content in the first line, we are defining a scene class with a construct method:

```python
class MyFirstAnimation(Scene):
    def construct(self):
        ...
```

This is the general formula of creating a single animation - you define a custom class that inherits from the [`Scene`](https://docs.manim.community/en/stable/reference/manim.scene.scene.Scene.html) class and has a `construct` method. `Scene` class is the higher-level building block of Manim which connects all related animations and objects into a single structure.

Next, we are creating two objects (a star and a circle) that belong to a `Mobject` class (mathematical object). This [`Mobject`](https://docs.manim.community/en/stable/reference_index/mobjects.html) class is a base data structure for many built-in mobjects like geometric shapes, vectors, coordinate systems, etc. Basically, everything that is not a scene and animation is a `Mobject`.

```python
class MyFirstAnimation(Scene):
    def construct(self):
        # Create basic mobjects
        star = Star(n=5, fill_color=RED, stroke_color=BLUE)
        circle = Circle(fill_color=DARK_BLUE, fill_opacity=.8, stroke_color=BLUE)
```

Then, we have the [`Animation`](https://docs.manim.community/en/stable/reference_index/animations.html) classes. In the above example, we are using 3 of them - `FadeIn`, `Transform` and `FadeOut`. All built-in `Animation` classes in manim accept mobjects as arguments and apply various effects to them. For example, `Transform` accepts two mobjects and plays out a smooth animation that converts the first one to the other.

```python
self.play(FadeIn(star, run_time=2))
# Wait for a second
self.wait()
# Transform star into a circle
self.play(Transform(star, circle))
self.wait(0.5)
# Remove the circle by fading it out
self.play(FadeOut(circle))
```

Every time you create an animation, you have to wrap it inside the `play` function so that they are rendered on the screen.

Lastly, we have the constants like `RED`, `BLUE`, `YELLOW`, `PI`, `TAU`, etc. These are part of the [`constants`](https://docs.manim.community/en/stable/reference/manim.constants.html) module of Manim and encode commonly-used values as variables and are imported in the first line of the snippet:

In [1]:
from manim import *

YELLOW, RED, BLUE

Manim Community v0.9.0

('#FFFF00', '#FC6255', '#58C4DD')

In [2]:
PI, TAU  # 2 * PI

(3.141592653589793, 6.283185307179586)

# Controlling Mobjects and their location

By default, all mobjects added to the screen gets displayed in the `ORIGIN`:

In [3]:
ORIGIN

array([0., 0., 0.])

Manim uses numpy arrays to represent the screen in `x`, `y`, `z` coordinates. `z` will stay 0 as long as you are animating in the 2D space. To shift an object a single unit in either `x` or `y` direction, you can use constants `LEFT`, `RIGHT`, `UP` and `DOWN`:

In [6]:
LEFT, RIGHT, UP, DOWN

(array([-1.,  0.,  0.]),
 array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([ 0., -1.,  0.]))

As an example, we will draw 4 mobjects at different locations in the screen and place a dot at the origin for reference:

```python
%%manim ShowCoordinates


class ShowCoordinates(Scene):
    def construct(self):
        # place a dot at the origin
        dot = Dot(radius=0.16, color=RED)
        # Add the dot to the screen
        self.add(dot)
        # Create 4 different mobjects and shift them from the origin
        square = Square().shift(2 * LEFT)
        triangle = Triangle().shift(2 * RIGHT)
        circle = Circle().shift(2 * DOWN)
        star = Star(n=7).shift(2 * UP)
        # Add all to the screen
        self.add(square, triangle, circle, star)
```

Since `LEFT`, `RIGHT`, etc. variables are Numpy arrays, they allow numeric operations that allow scaling them like above. There are also other built-in location variables like `UL` (UP + LEFT), `DR` (DOWN + RIGHT), etc.:

In [8]:
UL, DR

(array([-1.,  1.,  0.]), array([ 1., -1.,  0.]))

In the above snippet, we are using the `shift` method of the mobjects by passing their new coordinate location. Since `shift` is only a function, the actual shifting does not get animated. To display mobjects that aren't animated, we use the `add` method.

What if we wanted to animate that shifting motion? Well, you can just chain `shift` after the `animate` function like so:

```python 
%%manim -i ShowCoords2


class ShowCoords2(Scene):
    def construct(self):
        # place a dot at the origin
        dot = Dot(radius=0.16, color=RED)  # twice the usual size

        # Create 4 different mobjects and animate their shift
        new_locations = [2 * UL, 2 * UR, 2 * DL, 2 * DR]
        mobjects = [Square(), Triangle(), Circle(), Star(n=7)]

        for loc, mob in zip(new_locations, mobjects):
            self.play(mob.animate.shift(loc))

        # Add the dot with Create animation
        self.play(Create(dot))
```

In fact, with `animate` method, you can animate almost any type of change to an mobject. For example, mobjects have several methods that start with `set_*` that changes their attributes. Here is an example:

```python
%%manim -i AnimateAttribs


class AnimateAttribs(Scene):
    def construct(self):
        # Create a simple square
        square = Square(side_length=2)

        # Scale to twice the size
        self.play(square.animate.scale(2))
        # Rotate
        self.play(square.animate.rotate(PI / 3))  # Rotate 60 degrees
        # Change the fill color and opacity
        self.play(square.animate.set_fill(RED, opacity=0.7))
        self.wait(2)
```

# Animating functions

Let's get a bit more serious and learn how to draw functions and animate their creation. From now on, I will be using JupyterLab and its `%%manim` cell magic to render the manim output. The syntax is exactly the same as the CLI interface.

```python
%%manim -i -qh -o func_example FunctionExample
import numpy as np

class FunctionExample(Scene):
    def construct(self):
        axes = Axes(
            x_range=[-5, 5, .5],
            y_range=[-3, 4, 1],
            x_axis_config={"numbers_to_include": [-4, -3, 3, 4]},
            y_axis_config={"numbers_to_include": [-2, 2, 3]},
            tips=True
        )
        axes_labels=axes.get_axis_labels()
        # Get the graph of a simple functions
        graph = axes.get_graph(lambda x: np.sin(1/x), color=RED)
        # Set up its label
        graph_label = axes.get_graph_label(
            graph, x_val=1, direction=2 * UP + RIGHT,
           label=r'f(x) = \sin(\frac{1}{x})', color=DARK_BLUE
        )

        # Graph the axes components together
        axes_group = VGroup(axes, axes_labels)
        
        # Animate
        self.play(Create(axes_group), run_time=2)
        self.wait(0.25)
        self.play(Create(graph), run_time=3)
        self.play(Write(graph_label), run_time=2)   
```

To draw a 2D axes like in Matplotlib, call the [`Axes`](https://docs.manim.community/en/stable/reference/manim.mobject.coordinate_systems.Axes.html) class with the desired arguments. 

Next, we are using the [`get_graph`](https://docs.manim.community/en/stable/reference/manim.mobject.coordinate_systems.CoordinateSystem.html#manim.mobject.coordinate_systems.CoordinateSystem.get_graph) method, passing the function we want to draw. This built-in method only accepts single variable functions that return a one-to-one mapping between `x` and `y`. In the above example, we are drawing the graph of $f(x) = \sin(\frac{1}{x})$. 

```python
# Get the graph of a simple functions
graph = axes.get_graph(lambda x: np.sin(1/x), color=RED)
```
Optionally, you can place the function's label at a specific location using `get_graph_label`:

```python
# Set up its label
graph_label = axes.get_graph_label(
    graph, x_val=1, direction=2 * UP + RIGHT,
   label=r'f(x) = \sin(\frac{1}{x})', color=DARK_BLUE
)
```

Finally, we are creating a group of mobjects using the [`VGroup`](https://docs.manim.community/en/stable/reference/manim.mobject.types.vectorized_mobject.VGroup.html?highlight=vgroup) class. It allows simultaneous animations and transformations on multiple mobjects.

Also, don't forget to draw each mobject you created. Either use animation functions like `Create`/`Write` or simply use `self.add`.

# More cool examples

You didn't think I would leave without showing some signature animations of 3B1B, right?

I got to know about 3B1B from his Essence of Linear Algebra series and seeing a linear transformation of space completely blew my mind. The crazy part is that animating it is stupidly easy with Manim:

```python
%%manim -qh -o lin_transform LinearTransformExample

class LinearTransformExample(LinearTransformationScene):
    def __init__(self):
        LinearTransformationScene.__init__(
            self,
            show_coordinates=True,
            leave_ghost_vectors=True,
        )
        
    def construct(self):
        # Create the matrix that does the transform
        matrix = [[3, 1], 
                  [4, 2]]
        self.apply_matrix(matrix)
        self.wait(2)
```

Similarly, seeing functions graphed in 3D was really eye-opening because we are all used to drawing functions on the XY plane. You will realize how beautiful math can be when you look at functions like below:

```python
%%manim -qh -o threeDexample ThreeDSurface

class ThreeDSurface(ThreeDScene):
    def construct(self):
        res = 30
        self.set_camera_orientation(phi=50*DEGREES, theta=-30*DEGREES)
        
        def ripple(u, v):
            x = u
            y = v
            z = np.sin(10*(x**2 + y**2)) / 10
            return np.array([x, y, z])
        
        ripple_plane = ParametricSurface(
            ripple, resolution=(res, res),
            v_range=[-3, 3],
            u_range=[-3, 3],
            checkerboard_colors=None
        )
        # Set up the ripple plane
        ripple_plane.scale_about_point(1.5, ORIGIN)
        ripple_plane.set_style(fill_opacity=.5, stroke_color=ORANGE)
        # Create 3D axes
        axes = ThreeDAxes()
        # Animate
        self.add(axes)
        self.play(GrowFromCenter(ripple_plane), run_time=3)
        # Rotate around the Z axis for 20 seconds
        self.begin_ambient_camera_rotation()
        self.wait(20)
        self.stop_ambient_camera_rotation()
```

Hey, how about those non-linear transforms?

```python
%%manim -i -qh -o non_lin_transform NonLinearTransform


class NonLinearTransform(Scene):
    def construct(self):
        # Create the grid and add it to screen
        grid = NumberPlane()
        self.add(grid)
        self.play(Create(grid, run_time=3, lag_ratio=.1))
        
        self.wait()
        
        grid.prepare_for_nonlinear_transform()
        # Transform
        self.play(
        grid.animate.apply_function(
                    lambda p: p + np.array(
                        [np.cos(p[1]), np.exp(2*np.sin(p[0]) + np.tan(p[0])), 0,]
                )
            ),
            run_time=3,
        )
        
        self.wait()
```

Can it get any better than this? Of course it can!

What you learned today, though very cool already, is only a thin slice of what manim can do. The above animations are only what Grant Sanderson uses in his simple opening scenes. 

The library has a steep learning curve when you want to move beyond the built-in mobjects and animation classes. Implementing custom classes can be pretty verbose, often taking thousands lines of code for longer videos.

However, this shouldn't stop you if you truly love math and explaining it to others in novel and creative ways.

# Parting words

I apologize for turning this piece into too much of a "how-to" post. That's just my deep-rooted tendency to over-explain things. 

However, I felt that proper explanations were necessary since the Internet was full of outdated tutorials and videos. On top of that, there is that confusion when you accidentally use different versions of manim in a single project. 

I strongly recommend going through every page of the [documentation of the community version](https://docs.manim.community/en/stable/) if you want to be a die-hard manim animator. I also suggest you check out channels like [this](https://www.youtube.com/channel/UCK8XIGR5kRidIw2fWqwyHRA) that use Manim and read their source code. 