# Operator Overloading in Python OOP, Fun Tutorial
## Integrate you classes into Standard Python
<img src='images/pixabay.jpg'></img>
<figcaption style="text-align: center;">
    <strong>
        Photo by 
        <a href='https://pixabay.com/users/kiquebg-5133331/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=4256272'>kiquebg</a>
        on 
        <a href='https://pixabay.com/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=4256272'>Pixabay</a>
    </strong>
</figcaption>

You can change the functionality of an operator to suit your custom classes needs. In this tutorial, you will learn about a powerful concept of Object-oriented programming: *Operator Overloading* in Python.

### Introduction

There are close to 40 operators in Python. Each has a unique function and they all work with the built-ins of native Python. However, you might have noticed that there are more flexible ones such as '+' (plus), '\*' (asterisk), or '\[\]' (brackets) operators. Depending on what type of data structure you use them on, they behave differently:

In [12]:
4 + 5  # addition

9

In [13]:
["list1"] + ["list2"]  # Adding two lists

['list1', 'list2']

In [14]:
4 * 5  # multiplication

20

In [15]:
[1] * 5  # mulitplying lists

[1, 1, 1, 1, 1]

In [17]:
[1, 2, 3, 4, 5][2]  # slicing and creating lists

3

These are examples with the built-in types. But there are also custom packages that use these operators differently:

In [18]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

array + 4

array([5, 6, 7, 8, 9])

In [20]:
array + array

array([ 2,  4,  6,  8, 10])

In [21]:
array * 5

array([ 5, 10, 15, 20, 25])

Numpy's `ndarray`s seems to work different. Adding two arrays does it element-wise, instead of creating a longer array. 

This example of operators behaving differently for various classes is called *operator overloading*. So, how do we achieve this for custom classes? Let's say we are creating our own number class:

In [29]:
class Number:
    def __init__(self, num):
        self.num = num


num1 = Number(5)
num2 = Number(6)

num1 + num2

TypeError: unsupported operand type(s) for +: 'Number' and 'Number'

When we tried to add the two numbers (which is the most basic operation on numbers), we got a TypeError. We cannot even multiply them:

In [30]:
num1 * num2

TypeError: unsupported operand type(s) for *: 'Number' and 'Number'

Learning Operator Overloading will help us fix these type of errors.

### What powers operators under the hood: built-in special functions

Each operator has a built-in function that is being called every time we use them. These special functions have a naming convention which you have already seen. One example is the `__init__` function of constructions which is called every time we initialize an object. Here are the special functions for the most common operators:

In [35]:
ml = [1, 2, 3, 4]
ml.__len__()  # len() function

4

In [36]:
ml.__getitem__(3)  # slicing with []

4

In [38]:
ml.__add__([5, 6, 7])  # adding lists with + operator

[1, 2, 3, 4, 5, 6, 7]

You can get all the available special functions of an object using `dir()`:

In [39]:
dir(ml)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

So, special functions start and end with double-underscore. Every single operator, \*, /, -, +, >, <, >=, <=, +=, etc has its own special function that gets fired whenever we use them. And the cool thing is we can always change their behavior with Operator Overloading when writing custom classes. You can find the exhaustive list of operators [here](https://docs.python.org/3/library/operator.html).

In the coming sections, we will modify some of the operators for a custom class that implements vectors. 

### Operator Overloading: String Representation

We will be learning operator overloading by expanding on this simple Vector class:

In [40]:
class Vector:
    def __init__(self, components: list):
        self.components = components

The first two operators we will be modifying is related to string representation:

In [41]:
v1 = Vector([3, 6])
print(v1)

Printing the vector object `v1` gives its location in memory (more on that later). This information would be useless for the end user. So, it would be better if the `print` function provided a more informative output. If you notice, there are many classes which give useful printouts:

In [42]:
array = np.array([3, 5, 2, 6])
print(array)

[3 5 2 6]


Calling `print` on a Numpy array shows its data, not its memory representation. Imitating Numpy arrays, we also want our vector objects to print out their contents when called `print`. In other words, we want to change their string representation. 

There are two ways we can accomplish this using Python: using `__str__` and `__repr__` functions. Let's start with `__str__`. This function gets fired under the hood whenever `print` is called. Defining a new `__str__` function in our Vector class overrides its behavior:

In [64]:
class Vector:
    def __init__(self, components: list):
        self.components = components

    def __str__(self):
        custom_string = "I am a vector!"
        return custom_string

In [65]:
v1 = Vector([1, 2, 3])
print(v1)

I am a vector!


Using `__str__`, we can return any custom text. Below, I will make the function print the vector in a vertical, proper representation:

In [79]:
class Vector:
    def __init__(self, components: list):
        self.components = components

    def __str__(self):
        if len(self.components) == 2:
            custom_string = "[ {}\n  {} ]".format(
                self.components[0], self.components[1]
            )
        elif len(self.components) == 3:
            custom_string = "[ {}\n  {}\n  {} ]".format(
                self.components[0], self.components[1], self.components[2]
            )
        elif len(self.components) == 4:
            custom_string = "[ {}\n  {}\n  {}\n  {} ]".format(
                self.components[0],
                self.components[1],
                self.components[2],
                self.components[3],
            )
        else:
            custom_string = "[  {}\n   {}\n  ...\n   {} ]".format(
                self.components[0], self.components[1], self.components[-1]
            )
        return custom_string

In [67]:
v1 = Vector([1, 2, 3])
print(v1)

[ 1
  2
  3 ]


In [69]:
v2 = Vector([3, 5, 5, 2, 5])
print(v2)

[  3
   5
  ...
   5 ]


You can also change the string representation using `__repr__`. This function gets fired whenever we display objects in interactive session or in a Jupyter Notebook. The output of `__repr__` is usually a bit different from `__str__`. The main difference is that `__str__` should give information about the object while `__repr__` should show exactly how the object was initialized:

In [82]:
class Vector:
    def __init__(self, components: list):
        self.components = components

    def __str__(self):
        ...

    def __repr__(self):
        return f"Vector({str(self.components)})"

In [76]:
v1 = Vector([1, 2, 3, 4])
v1

Vector([1, 2, 3, 4])

Users should be able to reinitialize your object in this way using `repr`:

In [83]:
v1_clone = eval(repr(v1))  # repr() is an identical cousin of __repr__
v1_clone

Vector([1, 2, 3, 4])

Adding custom string representations is the first step towards a more user-friendly class design.

### Operator Overloading: Comparison

Say we have a simple Student class:

In [85]:
class Student:
    def __init__(self, name):
        self.name = name


s1 = Student("Barry Smith")
s2 = Student("Barry Smith")

s1 == s2

False

When checking if two students with the same name are the same, we get False. In this case, it might make sense because there can be multiple students with the same name. However, what if each student had a unique ID:

In [86]:
class Student:
    def __init__(self, name, student_id):
        self.name = name
        self.student_id = student_id


s1 = Student("Barry Smith", 121)
s2 = Student("Barry Smith", 121)

s1 == s2

False

Obviously, two students with the same name and ID should be the same person but Python still treats them differently. Recall that printing an object returned its memory location

In [87]:
print(s1)

In [88]:
print(s2)

As you can see, even though the data is the same for the two objects, their memory locations are different. And when comparing objects to each other Python compares their locations in memory. But some modules like Numpy compares arrays based on their data:

In [90]:
array1 = np.array([3, 6, 8])
array2 = np.array([3, 6, 8])

print(array1 == array2)

[ True  True  True]


So, it would also make sense to compare the objects of our Vector class based on *their* data. To accomplish this, we will use the special function of '==' equality operator called `__eq__()`. It accepts two arguments - `self` and `other`. Just like `self` was the reference to the current object, `other` is a reference to the other object that we are comparing:

In [127]:
class Vector:
    def __init__(self, components: list):
        self.components = components

    ...

    def __eq__(self, other):
        return all([c1 == c2 for c1, c2 in zip(self.components, other.components)])

In [128]:
v1 = Vector([2, 3, 4])
v2 = Vector([2, 3, 4])

v1 == v2

True

In [129]:
v3 = Vector([4, 5, 6, 6])
v4 = Vector([1, 4, 5, 8])

v3 == v4

False

We modified the `__eq__` method to return True if all components of the Vectors are equal.

There are also special functions for other comparison operators: `__lt__(a, b)` is equivalent to a < b, `__le(a, b)__` is equivalent to a <= b, etc. Again, refer to this [link](https://docs.python.org/3/library/operator.html) for the full list.

### Operator Overloading: Arithmetic Operations

It is time to define some of the common vector operations such as vector magnitude, multiplication, addition/subtraction. Let's start with vector magnitude. Since vector magnitude is also called the absolute value of a vector, it will be cool to overload `abs()` function to calculate this. Its special function is `__abs__()`:

In [136]:
import math


class Vector:
    def __init__(self, components: list):
        self.components = components

    ...

    def __abs__(self):
        return math.sqrt(sum([c ** 2 for c in self.components]))

In [137]:
v = Vector([2, 3, 4])
abs(v)

5.385164807134504

Next, let's add two vectors together (component-wise) when we use '+' operator. Its special function is `__add__`:

In [141]:
class Vector:
    def __init__(self, components: list):
        self.components = components

    ...

    def __repr__(self):
        return f"Vector({str(self.components)})"

    def __add__(self, other):
        result = [c1 + c2 for c1, c2 in zip(self.components, other.components)]

        return self.__class__(result)

In [142]:
v1 = Vector([1, 2, 3, 4])
v2 = Vector([2, 3, 5, 6])

v1 + v2

Vector([3, 5, 8, 10])

Pay attention to the `return` statement. We can access the class with itself using the `__class__` attribute and call its constructor.

Now, let's extend this addition to adding scalars to vectors:

In [156]:
class Vector:
    def __init__(self, components: list):
        self.components = components

    ...

    def __repr__(self):
        return f"Vector({str(self.components)})"

    def __add__(self, other):
        if isinstance(other, int) or isinstance(other, float):
            result = [other + c for c in self.components]
        else:
            result = [c1 + c2 for c1, c2 in zip(self.components, other.components)]

        return self.__class__(result)

In [159]:
v1 = Vector([1, 2, 3, 4])
v2 = Vector([2, 3, 5, 6])

v1 + 4

Vector([5, 6, 7, 8])

In [160]:
v1 + v2

Vector([3, 5, 8, 10])

Next would be multiplying vectors by scalars but that is easy enough to do yourself. 

Instead, we will finally see how to compute the dot product of two vectors. Python has a special operator '@' for matrix operations which we can overload:

In [175]:
class Vector:
    def __init__(self, components: list):
        self.components = components

    ...

    def __repr__(self):
        return f"Vector({str(self.components)})"

    def __matmul__(self, other):
        result = [c1 * c2 for c1, c2 in zip(self.components, other.components)]
        return sum(result)

In [176]:
v1 = Vector([1, 2, 3])
v2 = Vector([2, 3, 5])

v1 @ v2

23

Now, our Vector class is almost as function as real vectors!

### Summary

If you have been learning and using OOP for a time, you may have noticed a pattern: OOP concepts are super easy to understand, it is the actual programming part that is hard. Anyone could have understood today's topic, but being able to implement them in code speaks a lot about your programming skills. OOP is all about skill!

In this tutorial, you have added a powerful technique to your arsenal: Operator Overloading. Using this method you can harness the behavior of Python built-in operators while writing classes. For more information on the topic, I suggest these sources:

- [Operator and Function Overloading in Custom Python Classes @ Real Python](https://realpython.com/operator-function-overloading/)
- [Python Data Model, Official Documentation](https://docs.python.org/3/reference/datamodel.html#special-method-names)
- [Operator Overloading by Programiz](https://www.programiz.com/python-programming/operator-overloading)

### Further Reading on OOP
- [Differentiating Between Class and Instance-level Data in Python Object-oriented-programming (OOP)](https://codecrunch.org/differentiating-between-class-and-instance-level-data-in-python-object-oriented-programming-oop-e2141a23739e?source=your_stories_page-------------------------------------)
- [Python Inheritance: How to Use Existing Code All Around the World](https://towardsdev.com/python-inheritance-how-to-use-existing-code-all-around-the-world-bb43a6d8c71?source=your_stories_page-------------------------------------)