# Operator Overloading in Python OOP
## Integrate you classes into Standard Python
<img src='images/pixabay.jpg'></img>
<figcaption style="text-align: center;">
    <strong>
        Photo by 
        <a href='https://pixabay.com/users/kiquebg-5133331/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=4256272'>kiquebg</a>
        on 
        <a href='https://pixabay.com/?utm_source=link-attribution&utm_medium=referral&utm_campaign=image&utm_content=4256272'>Pixabay</a>
    </strong>
</figcaption>

You can change the functionality of an operator to suit your custom classes needs. In this tutorial, you will learn about a powerful concept of Object-oriented programming: *Operator Overloading* in Python.

### Introduction

There are close to 40 operators in Python. Each has a unique function and they all work with the built-ins of native Python. However, you might have noticed that there are more flexible ones such as '+' (plus), '\*' (asterisk), or '\[\]' (brackets) operators. Depending on what type of data structure you use them on, they behave differently:

In [12]:
4 + 5  # addition

9

In [13]:
["list1"] + ["list2"]  # Adding two lists

['list1', 'list2']

In [14]:
4 * 5  # multiplication

20

In [15]:
[1] * 5  # mulitplying lists

[1, 1, 1, 1, 1]

In [17]:
[1, 2, 3, 4, 5][2]  # slicing and creating lists

3

These are examples with the built-in types. But there are also custom packages that use these operators differently:

In [18]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

array + 4

array([5, 6, 7, 8, 9])

In [20]:
array + array

array([ 2,  4,  6,  8, 10])

In [21]:
array * 5

array([ 5, 10, 15, 20, 25])

Numpy's `ndarray`s seems to work different. Adding two arrays does it element-wise, instead of creating a longer array. 

This example of operators behaving differently for various classes is called *operator overloading*. So, how do we achieve this for custom classes? Let's say we are creating our own number class:

In [29]:
class Number:
    def __init__(self, num):
        self.num = num


num1 = Number(5)
num2 = Number(6)

num1 + num2

TypeError: unsupported operand type(s) for +: 'Number' and 'Number'

When we tried to add the two numbers (which is the most basic operation on numbers), we got a TypeError. We cannot even multiply them:

In [30]:
num1 * num2

TypeError: unsupported operand type(s) for *: 'Number' and 'Number'

Learning Operator Overloading will help us fix these type of errors.

### What powers operators under the hood: built-in special functions

Each operator has a built-in function that is being called every time we use them. These special functions have a naming convention which you have already seen. One example is the `__init__` function of constructions which is called every time we initialize an object. Here are the special functions for the most common operators:

In [35]:
ml = [1, 2, 3, 4]
ml.__len__()  # len() function

4

In [36]:
ml.__getitem__(3)  # slicing with []

4

In [38]:
ml.__add__([5, 6, 7])  # adding lists with + operator

[1, 2, 3, 4, 5, 6, 7]

You can get all the available special functions of an object using `dir()`:

In [39]:
dir(ml)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

So, special functions start and end with double-underscore. Every single operator, \*, /, -, +, >, <, >=, <=, +=, etc has its own special function that gets fired whenever we use them. And the cool thing is we can always change their behavior with Operator Overloading when writing custom classes. You can find the exhaustive list of operators [here](https://docs.python.org/3/library/operator.html).

In the coming sections, we will modify some of the operators for a custom class that implements vectors. 