# Cheat sheet - Julia basics

## Content

### Accessing help
#### Accessing help files and documentation
- Entering help mode with ? at an empty prompt

```julia
julia> ?
help?>
```

- Get help on a function with ?functionname

```julia
julia> ?
help?> first

first(coll)

  Get the first element of an iterable collection. Return the start point of an AbstractRange even if it is empty.
```

- Search for help on a topic with ?"topic" or apropos("topic")

```julia
julia> ?
help?> function
Functions are defined with the function keyword:

  function add(a, b)
      return a + b
  end
```


#### Comments
- Single line comments with #
```julia
# This is a single-line comment
```
- Multi-line comments with #= and =#
```julia
#= This is a
multi-line comment =#
```

#### Information about objects
- Get the structure of an object with describe()

- Get the type of an object with typeof()
```julia
julia> typeof(22/7)
Float64
```

### Using packages
- Define or describe what a package is
A package is similar to a folder in a computer and combines multiple interconnected scripts that contain functions and classes
- Entering package mode with ] at an empty prompt

```julia
julia> ]
(@v1.4) pkg>
```
- Install a new package with add
```julia
julia> ]
(@v1.4) pkg> add CSV
```
- Load a package with using
```julia
julia> using CSV
```
- Load a package with import without an alias
```julia
julia> import CSV
```
- Load a package with import with an alias
```julia
import DataFrames as df
```

### The working directory
- Define or describe the working directory
In a hierarchical system, the working directory is the root directory where you can access all scripts and functions/classes within. 
- Get the current directory with pwd()
```julia
julia> pwd()
"/home/bexgboost/articles"
```
- Set the current directory with cd()
```julia
julia> cd()
"/home/bexgboost/cheatsheets"
```

### Operators
#### Arithmetic operators
- Add two numbers with a + b
```julia
julia> a = 73; b = 37
julia> a + b
110
```
- Subtract one number from another with a - b
```julia
julia> a - b
36
```
- Multiply two numbers with a * b
```julia
julia> a * b
2701
```

- Divide one number by another with a / b

```julia
julia> 22 / 7
3.14285714
```

- Integer divide one number by another with a ÷ b; keyboard shortcut of \div TAB

```julia
julia> 22 ÷ 7
3
```

- Inverse divide one number by another with a \ b
```julia
julia> 5 \ 0
0
```

- Raise one number to the power of another with a ^ b
```julia
julia> 3 ^ 3
27
```

- Get the remainder after division with a % b
```julia
julia> 22 % 7
1
```

#### Assignment operators
- Assigning to objects with a = value
- Mutating field of objects with a.f = value
- Mutating elements of objects with a[i] = value

#### Numeric comparison operators
- Equal objects with ==
- Not equal objects with != 
- Greater than >
- Greater than or equal to >=
- Less than <
- Less than or equal to with <=
- Logical operators
- Logical not with ~a
- Shortcut and with a && b
- Elementwise and with a & b
- Shortcut or with a || b
- Elementwise or with a | b
- Elementwise xor (exclusive or) with a ⊻ b; keyboard shortcut of \xor TAB
- Elementwise nor (not or) with a ⊽ b; keyboard shortcut of \nor TAB
- Elementwise nand (not and) with a ⊼ b; keyboard shortcut of \nand TAB

#### Other operators
- Determine if a value is in an array with x in arr
- Access field in an object with a.f
- Pipe values to a function with value |> fn

Assignment operators
Assigning to objects with a = value
Mutating field of objects with a.f = value
Mutating elements of objects with a[i] = value
Numeric comparison operators
Equal objects with ==
Not equal objects with != 
Greater than >
Greater than or equal to >=
Less than <
Less than or equal to with <=
Logical operators
Logical not with ~a
Shortcut and with a && b
Elementwise and with a & b
Shortcut or with a || b
Elementwise or with a | b
Elementwise xor (exclusive or) with a ⊻ b; keyboard shortcut of \xor TAB
Elementwise nor (not or) with a ⊽ b; keyboard shortcut of \nor TAB
Elementwise nand (not and) with a ⊼ b; keyboard shortcut of \nand TAB
Other operators
Determine if a value is in an array with x in arr
Access field in an object with a.f
Pipe values to a function with value |> fn

### Getting started with vectors
- Define or describe what vectors are
A collection of items such as floats, integers, strings or a mix that allows duplicate values. Synonyms from other languages are lists, arrays, etc.

#### Creating vectors
- Creating vectors with square brackets, [x1, x2, x3]
```julia
julia> x = [1, 2, 3]
3-element Array{Int64,1}:
 1
 2
 3
```
- Creating vectors with specific element types using Vector{type}([x1, x2, x3])

```julia
julia> Vector{Float16}([1, 2, 3])
3-element Array{Float16,1}:
 1.0
 2.0
 3.0
```

- Creating a sequence of numbers from a to b with a:b

```julia
julia> 37:100
37:100
```

- Creating a sequence of numbers from a to b in steps of stp with a:stp:b
```julia
julia> 1:2:101
1:2:101
```

- A couple of examples of repeating values with repeat(a, inner, outer)

```julia
julia> repeat(1:2, inner=2)
4-element Array{Int64,1}:
 1
 1
 2
 2

julia> repeat(1:2, outer=2)
4-element Array{Int64,1}:
 1
 2
 1
 2

julia> repeat(1:2, inner=2, outer=2)
8-element Array{Int64,1}:
 1
 1
 2
 2
 1
 1
 2
 2
```

#### Vector functions
- Sorting vectors with sort(x)
```julia
julia> x = [9, 1, 4]; sort(x)
3-element Array{Int64,1}:
 1
 4
 9
```
- Reversing vectors with reverse(x)
```julia
julia> x = [9, 1, 4]; reverse(x)
3-element Array{Int64,1}:
 4
 1
 9
```
- Reversing in-place with reverse!(x)
```julia
julia> x = [9, 1, 4]; reverse!(x)
julia> x
3-element Array{Int64,1}:
 4
 1
 9
```
- Get a frequency table of counts with freqtable(x)
> See my earlier comment
- Get unique elements of a vector with unique(x)

- Appending ! to the function name to modify in-place

In [20]:
[1 2 3]

1×3 Array{Int64,2}:
 1  2  3

In [19]:
x = [6, 7, 1, 7]; freqtable(x)
x

UndefVarError: UndefVarError: freqtable not defined

#### Selecting vector elements
- Selecting the 6th element of a vector with x[6]
- Selecting the last element of a vector with x[end]
- Slicing elements two to six from a vector with x[2:6]
- Selecting the 2nd and 6th element of a vector with x[[2, 6]]
- Selecting elements equal to 5 with x[x .== 5]
- Selecting elements less than 5 with x[x .< 5]
- Selecting elements in the vector 2, 5, 8 with x[in([2, 5, 8]).(x)]

### Math functions
- Get the logarithm of a vector with log.(x)
- Get the exponential of a vector with exp.(x)
- Get the maximum of a vector with maximum(x)
- Get the minimum of a vector with minimum(x)
- Get the sum of a vector with sum(x)
- Loading the Statistics package with using Statistics; explain that this is needed for the following summary stats.
- Get the mean of a vector with mean(x)
- Get the median of a vector with median(x)
- Get quantiles of a vector with quantile(x, p)
- Round values of a vector with round.(x, digits = n)
- Get significant figures of values of a vector with round.(x, sigdigits = n)
- Get the ranking of vector elements with using StatsBase; ordinalrank(x)
- Get the variance of a vector with var(x)
- Get the standard deviation of a vector with std(x)
- Get the correlation between two vectors with cor(x, y)

### Getting started with characters and strings
- Describe or define the difference between characters and strings
- Creating a character variable with single quotes
- Creating a string variable with double quotes and triple-double quotes
- Getting a single character substring with \[ and positional indexing (possible show and example with begin or end)
- Getting a multiple character substring with \[ and positional indexing

#### Combining and splitting strings
- Combining several strings, including string variables, into a longer string with string()
- Interpolating strings with "$value" syntax
- Repeating strings with ^
- Splitting strings on a delimiter with split()

#### Finding and extracting matches
- Detecting the presence of a pattern in a string with occursin()
- Find the position of the first match in a string with findfirst()
- Creating a match object with match()
- Extracting complete matches from a match object with m.match

#### Mutate
- Convert a string to upper case with uppercase()
- Convert a string to lower case with lowercase()
- Convert a string to title case with titlecase()
- Replace matches of a pattern with a new string with replace()

### Getting started with data frames
- Setting up the environment: adding and using the DataFrames package
- Create a data frame with various column types (show numeric & text columns, how a single value can be broadcast to fill the whole column, how to define non-standard column names with spaces in the name)
- Select the third row from a data frame using \[ and row number
- Select a column from a data frame using \. and column name
- Select the second column from a data frame using \[ and column number
- Select an element from a data frame using \[ and row and column numbers

### Manipulating data frames
- Concatenate two data frames horizontally with hcat()
- Concatenate two data frames vertically with vcat()
- Filter for rows of a data frame with filter() (maybe use an anonymous function here)
- Filter for rows of a data frame with subset() 
- Select columns of a data frame with select()
- Select all columns of a data frame except those specified with select(Not())
- Rename columns of a data frame with rename(old => new)
- Add new columns to a data frame with transform()
- Calculate column summary statistics on data frame with combine()
- Calculate groupwise column summary statistics on data frame with groupby() and combine()
- Get rows of a data frame with distinct values in a column with unique(df, :col) 
- Order the rows of a data frame with sort()
- Get the rows of a data frame with the largest values of a column with df[partialsortperm(), :